/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public enum AkActionOnEventType {
  AkActionOnEventType_Stop = 0,
  AkActionOnEventType_Pause = 1,
  AkActionOnEventType_Resume = 2,
  AkActionOnEventType_Break = 3
}
