/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public enum ErrorLevel {
  ErrorLevel_Message = (1 << 0),
  ErrorLevel_Error = (1 << 1),
  ErrorLevel_All = ErrorLevel_Message|ErrorLevel_Error
}
